### ISSUE TITLE
PDF download - new feature

### ISSUE THREAD

**Issue by mrjono1** [ducas/veda-connect-net#1]
Hi ducas

this project has assisted me heaps thankyou, have you ever tried to get the veda previous enquiry api woking to download the pdf version of the report?

Cheers
mrjono1

**Comment by ducas** [comment]
hi

good to hear this helped. i found the lack of available information quite frustrating when starting on this.

no - i haven't... i didn't even realise it existed 😮 

feel like submitting a PR?

ducas

**Comment by mrjono1** [comment]
I may been to quick to ask for assistance believe I have figured it out, it still has wsdl xml warnings but it seems to be working. I'll try to package it up for a pull request in the next few weeks.

**Comment by ducas** [comment]
👍

**Comment by ducas** [comment]
@mrjono1 how did you go?

**Comment by mrjono1** [comment]
I went well :)
I haven't had a chance to do a pull request yet but here is most of the code, I did everything the same way as you did
Endpoint: https://cteau.vedaxml.com/sys2/previous-enquiry-v1
`public async Task<PreviousEnquiryResult> GetPdfAsync(string enquiryId)
        {
            var request = new previousEnquiryOperationRequest()
            {
                request = new previousEnquiryRequestType()
                {
                    enquiryId = enquiryId,
                    contentType = new string[] { "application/pdf" }
                }
            };

```
        var messages = new List<Helpers.Message>();
        EventHandler<MessageReceivedEventArgs> messageReceived = (o, args) => messages.Add(args.Message);

        MessageInspector.MessageReceived += messageReceived;
        previousEnquiryOperationResponse previousEnquiryResponse = null;
        try
        {
            previousEnquiryResponse = await _previousEnquiryclient.previousEnquiryOperationAsync(request);
            await Task.Delay(3000);
            MessageInspector.MessageReceived -= messageReceived;
        }
        catch (System.ServiceModel.CommunicationException exception)
        {
            if (messages[0] != null)
            {
                var doc = XDocument.Parse(messages[0].Content);
                var faultCode = doc.Descendants("faultcode").FirstOrDefault();
                var faultString = doc.Descendants("faultString").FirstOrDefault();

                if (faultString != null)
                {
                    var errorResult = new PreviousEnquiryResult
                    {
                        Response = null,
                        Headers = messages[0].Headers,
                        Content = messages[0].Content,
                        Error = faultString.Value
                    };
                    return errorResult;
                }
            }

            throw new ExternalException(exception,
               "VedaPreviousEnquiry",
               "previousEnquiryOperationAsync",
                   new KeyValuePair<string, object>("enquiryId", enquiryId));
        }
        catch (Exception exception)
        {
            throw new ExternalException(exception,
                "VedaPreviousEnquiry",
                "previousEnquiryOperationAsync",
                    new KeyValuePair<string, object>("enquiryId", enquiryId));
        }
        //System.ServiceModel.Channels.MessageFault
        var message = messages.FirstOrDefault();

        var result = new PreviousEnquiryResult
        {
            Response = previousEnquiryResponse.response,
            Headers = message?.Headers,
            Content = message?.Content
        };
        //SoapException
        return result;
    }`
```

basic usage as a stream
`
            var data = await GetPdfAsync(VedaEnquiryId);
                    Stream stream = new MemoryStream(data.Response.binaryData[0].Value);`

**Comment by ducas** [comment]
looking good...

the only reason i added message interception was so that i could store the xml elsewhere for later inspection. not sure it's really needed here. have you found the headers/content useful? does the error handler really need to inspect the raw message or can it get the detail from the exception?

**Comment by mrjono1** [comment]
I found the message interception very handy. 
-WCF isn't very good at parsing soap error messages, so this way I can find the error and act on different errors differently
-The Veda responses are so large its good to be able to read the whole thing to figure out what decisions I need to make

The error handler does not need to inspect the raw message, I shouldn't do it there anyway because of the chance of more XML exceptions.

**Comment by ducas** [comment]
ok. i just realised i had unintentionally left a 3s delay in the code too... 😞  that should probably be a bit smarter.

**Comment by ducas** [comment]
hey @mrjono1. just thought i'd ping you to see if you wanted to add this in. if not, can you please send the metadata url so i can generate proxy service reference?
